name: Deps
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Check deps
        uses: gabotechs/dep-tree-action@v0.6.2-patch-1
        with:
          entrypoints: src/index.ts

